<?php

namespace AppBundle\Repository;

/**
 * DapdaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DapdaRepository extends \Doctrine\ORM\EntityRepository
{
}
