<?php

namespace AppBundle\Repository;

/**
 * DatosDapdaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatosDapdaRepository extends \Doctrine\ORM\EntityRepository
{
}
